source 'https://rubygems.org'

gem 'rails', '5.1.4'
gem 'cone', path: '..'

group :development, :test do
  gem 'thin'
  gem 'pry-rails'
  gem 'capybara', '2.7.1'
  gem 'selenium-webdriver', '2.53.4'
  gem 'minitest-reporters', '1.0.8'
end
