source 'https://rubygems.org'

gem 'rails', '3.2.9'
gem 'cone', path: '..'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'jquery-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'thin'
  gem 'pry'
  gem 'pry-rails'
  gem 'capybara', '2.0.1'
  gem 'turn', '0.9.6'
end
